n1=int(input("Enter the first number:"))
n2=int(input("Enter the second number:"))
print("addition of the numbers:",n1+n2)
print("subtraction of the numbers:",n1-n2)
print("multiplication of the numbers:",n1*n2)
print("division of the numbers:",n1/n2)
print("mod of the numbers:",n1%n2)
print("floor division of the numbers:",n1//n2)
print("exponent of the numbers:",n1**n2)
